/**
 * Catálogo dos veículos de demonstração.
 *
 * São anúncios FICTÍCIOS, criados para exercitar a plataforma. Cada um é
 * gravado com `isDemo: true` e aparece marcado como "Demonstração" na
 * interface. Vendedores, preços e descrições não correspondem a ofertas reais.
 *
 * `busca` é o termo usado para procurar uma fotografia livre no Wikimedia
 * Commons; `anoNaFoto` indica se aceitamos apenas imagens cujo título confirme
 * o ano — quando não dá para confirmar, a foto é marcada como ilustrativa.
 */

import type { BodyType, Feature, Fuel, Transmission } from '../src/lib/enums'

export type DemoVehicle = {
  brand: string
  model: string
  trim: string
  year: number
  modelYear: number
  priceReais: number
  mileageKm: number
  fuel: Fuel
  transmission: Transmission
  bodyType: BodyType
  color: string
  doors: number
  city: string
  state: string
  description: string
  features: Feature[]
  /** Índice do vendedor de demonstração (ver prisma/seed.ts). */
  seller: number
  /** Termo de busca no Wikimedia Commons. */
  busca: string
  /** Palavras que o título do arquivo precisa conter para ser aceito. */
  exigeNoTitulo: string[]
  /** Situação inicial do anúncio no seed. */
  status?: 'PUBLISHED' | 'PENDING' | 'DRAFT' | 'PAUSED' | 'SOLD' | 'REJECTED'
}

export const DEMO_VEHICLES: DemoVehicle[] = [
  // ─── SUV ──────────────────────────────────────────────────────────────────
  {
    brand: 'Jeep',
    model: 'Compass',
    trim: 'Longitude 1.3 T270 AT6',
    year: 2022,
    modelYear: 2022,
    priceReais: 138900,
    mileageKm: 41200,
    fuel: 'FLEX',
    transmission: 'AUTOMATICO',
    bodyType: 'SUV',
    color: 'Cinza',
    doors: 4,
    city: 'Campinas',
    state: 'SP',
    description:
      'SUV de uso familiar, sempre em garagem coberta. Revisões feitas na concessionária até a última exigida pelo manual, com notas guardadas. Pneus trocados há cerca de oito mil quilômetros. Documentação em dia e sem multas. Aceito avaliação em agência de sua confiança antes da negociação.',
    features: [
      'Ar-condicionado digital',
      'Central multimídia',
      'Apple CarPlay / Android Auto',
      'Câmera de ré',
      'Sensor de estacionamento',
      'Controle de estabilidade',
      'Rodas de liga leve',
      'Piloto automático',
    ],
    seller: 0,
    busca: 'Jeep Compass 2022',
    exigeNoTitulo: ['jeep', 'compass'],
  },
  {
    brand: 'Toyota',
    model: 'RAV4',
    trim: 'Hybrid SX AWD',
    year: 2021,
    modelYear: 2022,
    priceReais: 249900,
    mileageKm: 58400,
    fuel: 'HIBRIDO',
    transmission: 'CVT',
    bodyType: 'SUV',
    color: 'Branco',
    doors: 4,
    city: 'Curitiba',
    state: 'PR',
    description:
      'Híbrido com consumo muito bom em ciclo urbano. Único dono, revisões em concessionária e manual com todos os carimbos. Bancos de couro sem desgaste aparente, sem uso de cadeirinha. Entrego com as duas chaves e o manual original. Sem histórico de sinistro.',
    features: [
      'Bancos de couro',
      'Teto solar',
      'Central multimídia',
      'Câmera de ré',
      'Controle de estabilidade',
      'Piloto automático',
      'Faróis de LED',
      'Único dono',
      'Revisões em concessionária',
    ],
    seller: 1,
    busca: 'Toyota RAV4 2021',
    exigeNoTitulo: ['toyota', 'rav4'],
  },
  {
    brand: 'Hyundai',
    model: 'Creta',
    trim: 'Action 1.6 AT',
    year: 2023,
    modelYear: 2023,
    priceReais: 119500,
    mileageKm: 27800,
    fuel: 'FLEX',
    transmission: 'AUTOMATICO',
    bodyType: 'SUV',
    color: 'Prata',
    doors: 4,
    city: 'Belo Horizonte',
    state: 'MG',
    description:
      'Creta de baixa quilometragem, usado apenas na cidade durante a semana. Ainda dentro do período de garantia de fábrica. Nunca precisou de funilaria, pintura original em todas as peças. Troca de óleo feita no prazo, com registro no aplicativo da marca.',
    features: [
      'Ar-condicionado digital',
      'Central multimídia',
      'Apple CarPlay / Android Auto',
      'Câmera de ré',
      'Rodas de liga leve',
      'Freios ABS',
      'Airbag duplo',
    ],
    seller: 2,
    busca: 'Hyundai Creta',
    exigeNoTitulo: ['hyundai', 'creta'],
  },
  {
    brand: 'Volkswagen',
    model: 'T-Cross',
    trim: 'Highline 1.4 TSI',
    year: 2020,
    modelYear: 2021,
    priceReais: 112900,
    mileageKm: 63500,
    fuel: 'FLEX',
    transmission: 'AUTOMATICO',
    bodyType: 'SUV',
    color: 'Azul',
    doors: 4,
    city: 'Porto Alegre',
    state: 'RS',
    description:
      'SUV compacto bem equipado, com o pacote Highline completo. Segundo dono, comprado com trinta mil quilômetros. Pneus com aproximadamente 60% de vida útil. Sem retoque de pintura. Aceito troca por hatch de menor valor com volta em dinheiro.',
    features: [
      'Ar-condicionado digital',
      'Central multimídia',
      'Apple CarPlay / Android Auto',
      'Câmera de ré',
      'Sensor de estacionamento',
      'Piloto automático',
      'Rodas de liga leve',
      'Faróis de LED',
    ],
    seller: 0,
    busca: 'Volkswagen T-Cross',
    exigeNoTitulo: ['t-cross'],
  },

  // ─── Sedã ─────────────────────────────────────────────────────────────────
  {
    brand: 'Toyota',
    model: 'Corolla',
    trim: 'Altis Premium Hybrid',
    year: 2022,
    modelYear: 2023,
    priceReais: 179900,
    mileageKm: 34900,
    fuel: 'HIBRIDO',
    transmission: 'CVT',
    bodyType: 'SEDA',
    color: 'Preto',
    doors: 4,
    city: 'São Paulo',
    state: 'SP',
    description:
      'Corolla híbrido na versão topo de linha. Carro de executivo, rodava principalmente em rodovia. Bateria do sistema híbrido sem qualquer alerta no painel. Todas as revisões na concessionária, garantia estendida transferível até o fim do próximo ano.',
    features: [
      'Bancos de couro',
      'Bancos com regulagem elétrica',
      'Central multimídia',
      'Apple CarPlay / Android Auto',
      'Câmera de ré',
      'Sensor de estacionamento',
      'Piloto automático',
      'Faróis de LED',
      'Revisões em concessionária',
    ],
    seller: 1,
    busca: 'Toyota Corolla 2022 sedan',
    exigeNoTitulo: ['toyota', 'corolla'],
  },
  {
    brand: 'Honda',
    model: 'Civic',
    trim: 'EXL 2.0 CVT',
    year: 2019,
    modelYear: 2020,
    priceReais: 124900,
    mileageKm: 78200,
    fuel: 'FLEX',
    transmission: 'CVT',
    bodyType: 'SEDA',
    color: 'Cinza',
    doors: 4,
    city: 'Ribeirão Preto',
    state: 'SP',
    description:
      'Civic EXL com acabamento em couro e multimídia original. Mecânica revisada, correia e fluidos trocados dentro do prazo. Pequeno desgaste no volante, compatível com a quilometragem — está nas fotos. Documentação quitada, sem restrição financeira.',
    features: [
      'Bancos de couro',
      'Central multimídia',
      'Câmera de ré',
      'Piloto automático',
      'Controle de estabilidade',
      'Rodas de liga leve',
      'Freios ABS',
    ],
    seller: 3,
    busca: 'Honda Civic 2019 sedan',
    exigeNoTitulo: ['honda', 'civic'],
  },
  {
    brand: 'BMW',
    model: 'Série 3',
    trim: '320i Sport GP',
    year: 2018,
    modelYear: 2019,
    priceReais: 168000,
    mileageKm: 92300,
    fuel: 'GASOLINA',
    transmission: 'AUTOMATICO',
    bodyType: 'SEDA',
    color: 'Branco',
    doors: 4,
    city: 'Rio de Janeiro',
    state: 'RJ',
    description:
      'Sedã premium com manutenção feita em oficina especializada na marca. Suspensão revisada no ano passado, com nota fiscal. Bancos elétricos funcionando perfeitamente. Pneus novos, trocados há menos de cinco mil quilômetros. Laudo cautelar recente disponível para quem tiver interesse real.',
    features: [
      'Bancos de couro',
      'Bancos com regulagem elétrica',
      'Teto solar',
      'Central multimídia',
      'Sensor de estacionamento',
      'Controle de estabilidade',
      'Rodas de liga leve',
      'Faróis de LED',
    ],
    seller: 4,
    busca: 'BMW 320i F30',
    exigeNoTitulo: ['bmw'],
  },
  {
    brand: 'Chevrolet',
    model: 'Onix Plus',
    trim: 'LTZ 1.0 Turbo AT',
    year: 2021,
    modelYear: 2021,
    priceReais: 89900,
    mileageKm: 55100,
    fuel: 'FLEX',
    transmission: 'AUTOMATICO',
    bodyType: 'SEDA',
    color: 'Vermelho',
    doors: 4,
    city: 'Goiânia',
    state: 'GO',
    description:
      'Sedã compacto econômico, ideal para quem roda muito na cidade. Motor 1.0 turbo com bom desempenho e consumo. Multimídia com espelhamento de celular. Sem detalhes na lataria, apenas marcas de uso normal no para-choque traseiro, visíveis nas fotos.',
    features: [
      'Ar-condicionado',
      'Central multimídia',
      'Apple CarPlay / Android Auto',
      'Câmera de ré',
      'Freios ABS',
      'Airbag duplo',
      'Vidros elétricos',
    ],
    seller: 2,
    busca: 'Chevrolet Onix Plus',
    exigeNoTitulo: ['onix'],
  },

  // ─── Hatch ────────────────────────────────────────────────────────────────
  {
    brand: 'Volkswagen',
    model: 'Golf',
    trim: 'GTI 2.0 TSI',
    year: 2017,
    modelYear: 2018,
    priceReais: 149900,
    mileageKm: 71400,
    fuel: 'GASOLINA',
    transmission: 'AUTOMATIZADO',
    bodyType: 'HATCH',
    color: 'Branco',
    doors: 4,
    city: 'Florianópolis',
    state: 'SC',
    description:
      'Golf GTI original, sem preparação e sem remap. Câmbio DSG com revisão do fluido feita no prazo. Bancos esportivos em ótimo estado. Foi meu carro de fim de semana nos últimos três anos, por isso a quilometragem baixa para o ano. Entrego revisado.',
    features: [
      'Ar-condicionado digital',
      'Central multimídia',
      'Câmbio com aletas no volante',
      'Rodas de liga leve',
      'Faróis de LED',
      'Controle de estabilidade',
      'Freios ABS',
    ],
    seller: 4,
    busca: 'Volkswagen Golf GTI Mk7',
    exigeNoTitulo: ['golf'],
  },
  {
    brand: 'Fiat',
    model: 'Argo',
    trim: 'Drive 1.3 Firefly',
    year: 2021,
    modelYear: 2022,
    priceReais: 74900,
    mileageKm: 48900,
    fuel: 'FLEX',
    transmission: 'MANUAL',
    bodyType: 'HATCH',
    color: 'Branco',
    doors: 4,
    city: 'Salvador',
    state: 'BA',
    description:
      'Hatch econômico e fácil de manter. Carro de uso diário, sempre com manutenção em dia em oficina de confiança. Ar-condicionado gelando bem, sem ruído no motor. Pneus com meia vida. Ideal para quem procura primeiro carro ou uso em aplicativo.',
    features: [
      'Ar-condicionado',
      'Direção elétrica',
      'Vidros elétricos',
      'Travas elétricas',
      'Freios ABS',
      'Airbag duplo',
    ],
    seller: 3,
    busca: 'Fiat Argo',
    exigeNoTitulo: ['fiat', 'argo'],
  },
  {
    brand: 'Peugeot',
    model: '208',
    trim: 'Griffe 1.6 AT',
    year: 2020,
    modelYear: 2021,
    priceReais: 82500,
    mileageKm: 52300,
    fuel: 'FLEX',
    transmission: 'AUTOMATICO',
    bodyType: 'HATCH',
    color: 'Cinza',
    doors: 4,
    city: 'Niterói',
    state: 'RJ',
    description:
      'Hatch bem equipado, com painel digital e multimídia de série. Sempre guardado em garagem, pintura preservada. Sem retoques. Revisões feitas conforme o manual. Aceito avaliação mecânica prévia por conta do comprador.',
    features: [
      'Ar-condicionado digital',
      'Central multimídia',
      'Apple CarPlay / Android Auto',
      'Câmera de ré',
      'Rodas de liga leve',
      'Faróis de LED',
      'Freios ABS',
    ],
    seller: 0,
    busca: 'Peugeot 208 2020',
    exigeNoTitulo: ['peugeot', '208'],
  },
  {
    brand: 'Renault',
    model: 'Sandero',
    trim: 'Zen 1.0 SCe',
    year: 2019,
    modelYear: 2020,
    priceReais: 57900,
    mileageKm: 89700,
    fuel: 'FLEX',
    transmission: 'MANUAL',
    bodyType: 'HATCH',
    color: 'Prata',
    doors: 4,
    city: 'Fortaleza',
    state: 'CE',
    description:
      'Carro simples, honesto e barato de manter. Porta-malas grande para a categoria. Usado no trajeto casa-trabalho, sem rodar em estrada de terra. Amortecedores trocados no ano passado. Documentação em dia, IPVA pago.',
    features: ['Ar-condicionado', 'Direção elétrica', 'Vidros elétricos', 'Freios ABS', 'Airbag duplo'],
    seller: 2,
    busca: 'Renault Sandero',
    exigeNoTitulo: ['renault', 'sandero'],
  },

  // ─── Picape ───────────────────────────────────────────────────────────────
  {
    brand: 'Toyota',
    model: 'Hilux',
    trim: 'SRV 2.8 4x4 Diesel AT',
    year: 2021,
    modelYear: 2021,
    priceReais: 279900,
    mileageKm: 96500,
    fuel: 'DIESEL',
    transmission: 'AUTOMATICO',
    bodyType: 'PICAPE',
    color: 'Prata',
    doors: 4,
    city: 'Cuiabá',
    state: 'MT',
    description:
      'Picape usada em fazenda, com manutenção rigorosa e registro de todas as revisões. Tração 4x4 funcionando perfeitamente. Caçamba com protetor desde nova. Pneus AT com boa profundidade de sulco. Vendo por não usar mais no dia a dia.',
    features: [
      'Tração 4x4',
      'Ar-condicionado digital',
      'Central multimídia',
      'Câmera de ré',
      'Sensor de estacionamento',
      'Engate para reboque',
      'Bancos de couro',
      'Controle de estabilidade',
    ],
    seller: 1,
    busca: 'Toyota Hilux 2021',
    exigeNoTitulo: ['hilux'],
  },
  {
    brand: 'Ford',
    model: 'Ranger',
    trim: 'XLT 3.2 4x4 Diesel',
    year: 2019,
    modelYear: 2020,
    priceReais: 212000,
    mileageKm: 118300,
    fuel: 'DIESEL',
    transmission: 'AUTOMATICO',
    bodyType: 'PICAPE',
    color: 'Azul',
    doors: 4,
    city: 'Londrina',
    state: 'PR',
    description:
      'Ranger diesel com motor cinco cilindros, forte para reboque. Engate instalado de fábrica. Manutenção preventiva sempre em dia, com filtros e fluidos trocados no prazo. Alguns riscos na caçamba por uso de trabalho, mostrados nas fotos.',
    features: [
      'Tração 4x4',
      'Engate para reboque',
      'Ar-condicionado digital',
      'Central multimídia',
      'Câmera de ré',
      'Controle de estabilidade',
      'Rodas de liga leve',
    ],
    seller: 4,
    busca: 'Ford Ranger 2019',
    exigeNoTitulo: ['ford', 'ranger'],
  },
  {
    brand: 'Fiat',
    model: 'Toro',
    trim: 'Freedom 1.3 T270 AT6',
    year: 2022,
    modelYear: 2022,
    priceReais: 132900,
    mileageKm: 39400,
    fuel: 'FLEX',
    transmission: 'AUTOMATICO',
    bodyType: 'PICAPE',
    color: 'Branco',
    doors: 4,
    city: 'Uberlândia',
    state: 'MG',
    description:
      'Picape intermediária de uso urbano, nunca fez trabalho pesado. Caçamba sem amassados, com capota marítima inclusa. Multimídia com espelhamento. Carro de garagem, sem exposição ao sol. Revisões feitas na rede autorizada.',
    features: [
      'Ar-condicionado',
      'Central multimídia',
      'Apple CarPlay / Android Auto',
      'Câmera de ré',
      'Sensor de estacionamento',
      'Rodas de liga leve',
      'Freios ABS',
    ],
    seller: 3,
    busca: 'Fiat Toro',
    exigeNoTitulo: ['fiat', 'toro'],
  },

  // ─── Esportivo ────────────────────────────────────────────────────────────
  {
    brand: 'Porsche',
    model: '911',
    trim: 'Carrera S 3.0',
    year: 2018,
    modelYear: 2018,
    priceReais: 749000,
    mileageKm: 28600,
    fuel: 'GASOLINA',
    transmission: 'AUTOMATIZADO',
    bodyType: 'ESPORTIVO',
    color: 'Preto',
    doors: 2,
    city: 'São Paulo',
    state: 'SP',
    description:
      'Esportivo de coleção, mantido em garagem climatizada e usado poucas vezes por ano. Todas as revisões feitas na concessionária, com histórico completo. Sem qualquer modificação em relação ao original. Pneus e freios com desgaste mínimo. Vendo com toda a documentação e manuais.',
    features: [
      'Bancos de couro',
      'Bancos com regulagem elétrica',
      'Central multimídia',
      'Câmbio com aletas no volante',
      'Controle de estabilidade',
      'Rodas de liga leve',
      'Faróis de LED',
      'Único dono',
      'Revisões em concessionária',
    ],
    seller: 4,
    busca: 'Porsche 911 991',
    exigeNoTitulo: ['porsche', '911'],
  },
  {
    brand: 'Ford',
    model: 'Mustang',
    trim: 'GT 5.0 V8',
    year: 2018,
    modelYear: 2019,
    priceReais: 389000,
    mileageKm: 42100,
    fuel: 'GASOLINA',
    transmission: 'AUTOMATICO',
    bodyType: 'ESPORTIVO',
    color: 'Vermelho',
    doors: 2,
    city: 'Brasília',
    state: 'DF',
    description:
      'Mustang GT com motor V8 original e escapamento de fábrica. Sem preparação. Carro de fim de semana, sempre abastecido com combustível premium. Revisões em oficina especializada. Bancos e volante em ótimo estado. Aceito laudo cautelar completo.',
    features: [
      'Bancos de couro',
      'Bancos com regulagem elétrica',
      'Central multimídia',
      'Câmbio com aletas no volante',
      'Rodas de liga leve',
      'Faróis de LED',
      'Controle de estabilidade',
    ],
    seller: 1,
    busca: 'Ford Mustang GT 2018',
    exigeNoTitulo: ['mustang'],
  },
  {
    brand: 'Chevrolet',
    model: 'Camaro',
    trim: 'SS 6.2 V8',
    year: 2017,
    modelYear: 2017,
    priceReais: 329000,
    mileageKm: 61200,
    fuel: 'GASOLINA',
    transmission: 'AUTOMATICO',
    bodyType: 'ESPORTIVO',
    color: 'Amarelo',
    doors: 2,
    city: 'Balneário Camboriú',
    state: 'SC',
    description:
      'Camaro SS na cor amarela, bastante procurado. Motor V8 com manutenção feita por especialista. Pneus traseiros novos. Pequeno desgaste no banco do motorista, compatível com o uso. Documentação em ordem e sem restrição.',
    features: [
      'Bancos de couro',
      'Central multimídia',
      'Câmbio com aletas no volante',
      'Câmera de ré',
      'Rodas de liga leve',
      'Controle de estabilidade',
    ],
    seller: 0,
    busca: 'Chevrolet Camaro 2017',
    exigeNoTitulo: ['camaro'],
  },

  // ─── Elétrico / outros ────────────────────────────────────────────────────
  {
    brand: 'Nissan',
    model: 'Leaf',
    trim: '40 kWh',
    year: 2021,
    modelYear: 2021,
    priceReais: 189900,
    mileageKm: 31400,
    fuel: 'ELETRICO',
    transmission: 'AUTOMATICO',
    bodyType: 'HATCH',
    color: 'Branco',
    doors: 4,
    city: 'São Paulo',
    state: 'SP',
    description:
      'Elétrico com autonomia adequada para uso urbano. Bateria com saúde acima de noventa por cento no último diagnóstico, feito na concessionária. Acompanha cabo de recarga original. Custo de manutenção muito baixo. Vendo por mudança para fora do país.',
    features: [
      'Ar-condicionado digital',
      'Central multimídia',
      'Apple CarPlay / Android Auto',
      'Câmera de ré',
      'Piloto automático',
      'Faróis de LED',
      'Único dono',
    ],
    seller: 2,
    busca: 'Nissan Leaf 2021',
    exigeNoTitulo: ['nissan', 'leaf'],
  },
  {
    brand: 'Chevrolet',
    model: 'Spin',
    trim: 'LTZ 1.8 AT 7 lugares',
    year: 2020,
    modelYear: 2021,
    priceReais: 89900,
    mileageKm: 87600,
    fuel: 'FLEX',
    transmission: 'AUTOMATICO',
    bodyType: 'MINIVAN',
    color: 'Prata',
    doors: 4,
    city: 'Guarulhos',
    state: 'SP',
    description:
      'Minivan de sete lugares, espaço interno muito bom para família grande. Terceira fileira pouco usada. Ar-condicionado com saídas traseiras. Manutenção em dia, sem pendências. Bom para uso em transporte por aplicativo na categoria maior.',
    features: [
      'Ar-condicionado',
      'Central multimídia',
      'Câmera de ré',
      'Sensor de estacionamento',
      'Rodas de liga leve',
      'Freios ABS',
      'Airbag duplo',
    ],
    seller: 3,
    busca: 'Chevrolet Spin',
    exigeNoTitulo: ['spin'],
    status: 'PENDING',
  },

  // ─── Estados não publicados, para exercitar painel e moderação ───────────
  {
    brand: 'Volkswagen',
    model: 'Polo',
    trim: 'Highline 200 TSI',
    year: 2021,
    modelYear: 2022,
    priceReais: 97900,
    mileageKm: 44100,
    fuel: 'FLEX',
    transmission: 'AUTOMATICO',
    bodyType: 'HATCH',
    color: 'Cinza',
    doors: 4,
    city: 'Santo André',
    state: 'SP',
    description:
      'Hatch premium da categoria, com painel digital e bom acabamento interno. Carro de garagem, sem detalhes na pintura. Revisões feitas na rede autorizada, com registro no sistema da marca. Documentação quitada.',
    features: [
      'Ar-condicionado digital',
      'Central multimídia',
      'Apple CarPlay / Android Auto',
      'Câmera de ré',
      'Rodas de liga leve',
      'Faróis de LED',
    ],
    seller: 0,
    busca: 'Volkswagen Polo 2021',
    exigeNoTitulo: ['polo'],
    status: 'PENDING',
  },
  {
    brand: 'Honda',
    model: 'Fit',
    trim: 'EXL 1.5 CVT',
    year: 2019,
    modelYear: 2019,
    priceReais: 79900,
    mileageKm: 68400,
    fuel: 'FLEX',
    transmission: 'CVT',
    bodyType: 'HATCH',
    color: 'Prata',
    doors: 4,
    city: 'Campinas',
    state: 'SP',
    description:
      'Hatch com espaço interno muito acima da média e bancos mágicos. Ótimo estado de conservação, sempre revisado na concessionária. Ideal para família pequena que precisa de porta-malas grande.',
    features: ['Ar-condicionado', 'Central multimídia', 'Câmera de ré', 'Freios ABS', 'Airbag duplo'],
    seller: 3,
    busca: 'Honda Fit 2019',
    exigeNoTitulo: ['honda', 'fit'],
    status: 'PAUSED',
  },
  {
    brand: 'Jeep',
    model: 'Renegade',
    trim: 'Sport 1.8 AT',
    year: 2018,
    modelYear: 2019,
    priceReais: 84900,
    mileageKm: 97200,
    fuel: 'FLEX',
    transmission: 'AUTOMATICO',
    bodyType: 'SUV',
    color: 'Verde',
    doors: 4,
    city: 'Sorocaba',
    state: 'SP',
    description:
      'SUV compacto vendido recentemente por este anúncio. Mantido aqui como histórico de venda concluída pela plataforma.',
    features: ['Ar-condicionado', 'Central multimídia', 'Rodas de liga leve', 'Freios ABS'],
    seller: 2,
    busca: 'Jeep Renegade',
    exigeNoTitulo: ['jeep', 'renegade'],
    status: 'SOLD',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'Classe C',
    trim: 'C 250 Sport',
    year: 2016,
    modelYear: 2017,
    priceReais: 159900,
    mileageKm: 104500,
    fuel: 'GASOLINA',
    transmission: 'AUTOMATICO',
    bodyType: 'SEDA',
    color: 'Preto',
    doors: 4,
    city: 'Vitória',
    state: 'ES',
    description:
      'Sedã premium com acabamento em couro e teto solar panorâmico. Manutenção sempre feita em oficina especializada na marca, com notas fiscais guardadas. Suspensão e freios revisados. Pneus com boa vida útil restante.',
    features: [
      'Bancos de couro',
      'Bancos com regulagem elétrica',
      'Teto solar',
      'Central multimídia',
      'Sensor de estacionamento',
      'Controle de estabilidade',
      'Faróis de LED',
    ],
    seller: 4,
    busca: 'Mercedes-Benz C-Class W205',
    exigeNoTitulo: ['mercedes'],
  },
]
